import test from 'node:test';
import assert from 'node:assert/strict';
import {seed,blankVisit,saveVisit,cancelVisit,aggregate,selectVisits,safeSummary,day,shiftDay,patterns,adjustStock} from '../lib/health.ts';
function fixture(){const s=seed();const v={...blankVisit(),studentId:'s4',symptoms:['두통','복통'],usage:{band:2}};return {s,v};}
test('visit save, replay, edit, discharge and cancellation conserve inventory',()=>{const {s,v}=fixture();const a=saveVisit(s,v);assert.equal(a.batches[0].quantity,84);const b=saveVisit(a,v);assert.equal(b.batches[0].quantity,84);assert.equal(b.visits.length,a.visits.length);assert.equal(b.movements.length,a.movements.length);const c=saveVisit(b,{...v,usage:{band:5}});assert.equal(c.batches[0].quantity,81);const d=saveVisit(c,{...v,usage:{band:1},status:'교실 복귀',exitAt:new Date().toISOString()});assert.equal(d.batches[0].quantity,85);const e=cancelVisit(d,v.id);assert.equal(e.batches[0].quantity,86);assert.deepEqual(cancelVisit(e,v.id),e);assert.equal(selectVisits(e,day(),day()).some(x=>x.id===v.id),false);});
test('insufficient stock leaves all original records and lots untouched',()=>{const {s,v}=fixture();const before=structuredClone(s);assert.throws(()=>saveVisit(s,{...v,usage:{band:1,gauze:999}}),/재고/);assert.deepEqual(s,before);});
test('expired lots are excluded for new usage; allocation is earliest expiry first',()=>{const {s,v}=fixture();s.batches.unshift({id:'expired',itemId:'band',lot:'old',quantity:50,expires:shiftDay(day(),-1)},{id:'soon',itemId:'band',lot:'soon',quantity:1,expires:day()});const next=saveVisit(s,v);const saved=next.visits.find(x=>x.id===v.id)!;assert.deepEqual(saved.allocations,[{batchId:'soon',quantity:1},{batchId:'b1',quantity:1}]);assert.equal(next.batches[0].quantity,50);});
test('empty temperature and zero remain distinct; invalid quantities rejected',()=>{const {s,v}=fixture();assert.equal(saveVisit(s,v).visits[0].temperature,null);assert.equal(saveVisit(s,{...v,temperature:0}).visits[0].temperature,0);assert.throws(()=>saveVisit(s,{...v,usage:{band:1.5}}),/정수/);assert.throws(()=>saveVisit(s,{...v,temperature:NaN}),/체온/);});
test('discharge and guardian handover chronology is validated',()=>{const {s,v}=fixture();assert.throws(()=>saveVisit(s,{...v,status:'귀가'}),/퇴실/);assert.throws(()=>saveVisit(s,{...v,status:'귀가',exitAt:new Date().toISOString()}),/연락/);assert.throws(()=>saveVisit(s,{...v,status:'교실 복귀',exitAt:new Date(Date.parse(v.at)-1000).toISOString()}),/퇴실/);});
test('active students cannot receive duplicate concurrent stays',()=>{const {s,v}=fixture();assert.throws(()=>saveVisit(s,{...v,studentId:'s0'}),/이미/);});
test('aggregate counts distinct students separately and respects grade and date',()=>{const {s,v}=fixture();const a=saveVisit(s,v);const rows=selectVisits(a,day(),day(),'5');const stats=aggregate(a,rows);assert.equal(stats.visits,3);assert.equal(stats.students,2);assert.equal(stats.symptoms['두통'],2);assert.equal(stats.symptoms['복통'],1);assert.equal(selectVisits(a,shiftDay(day(),1),shiftDay(day(),2)).length,0);});
test('AI boundary only returns allowlisted fields and suppresses small groups',()=>{const {s,v}=fixture();const safe=safeSummary(s,[v],day(),day(),'5',3);assert.equal(safe.studentCount,null);assert.equal(safe.visitCount,null);assert.deepEqual(Object.keys(safe),['period','target','visitCount','studentCount','homeCount']);assert.equal(JSON.stringify(safe).includes('s4'),false);});
test('repeat rules report actual evidence counts',()=>{const {s,v}=fixture();s.visits=[v,{...v,id:'second',at:new Date(Date.now()-86400000).toISOString()},{...v,id:'third',at:new Date(Date.now()-2*86400000).toISOString()}];const result=patterns(s,30,3,true);assert.equal(result.length,2);assert.equal(result[0].visits.length,3);assert.equal(patterns(s,1,3,true).length,0);});
test('manual stock movements cannot produce negative inventory',()=>{const {s}=fixture();assert.throws(()=>adjustStock(s,'b1',-100,'폐기'),/재고/);assert.equal(adjustStock(s,'b1',4,'입고').batches[0].quantity,90);});

