'use client';
import {useRef,useState} from 'react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {Student} from '@/lib/health';
import {detectHeader,previewStudents,type Columns} from '@/lib/student-import';
export function StudentImport({existing,onClose,onImport}:{existing:Student[];onClose:()=>void;onImport:(students:Student[])=>void}){
 const [sheets,setSheets]=useState<Record<string,unknown[][]>>({});const [sheet,setSheet]=useState('');const [header,setHeader]=useState(0);const [columns,setColumns]=useState<Columns>({name:-1,grade:-1,room:-1,number:-1});const [grade,setGrade]=useState('');const [room,setRoom]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const lock=useRef(false);
 const rows=sheets[sheet]??[];const preview=previewStudents(rows,header,columns,grade,room,existing);
 function select(name:string,data=sheets){setSheet(name);const found=detectHeader(data[name]??[]);setHeader(found.row);setColumns(found.columns);}
 async function load(file?:File){if(!file)return;setBusy(true);setError('');setSheets({});setSheet('');try{if(!/\.(xlsx|xls)$/i.test(file.name))throw Error('Excel 파일(.xlsx, .xls)을 선택해 주세요.');if(file.size>10*1024*1024)throw Error('10MB 이하의 명단 파일을 선택해 주세요.');const XLSX=await import('xlsx');const book=XLSX.read(await file.arrayBuffer(),{type:'array',sheetRows:10002,cellFormula:false,cellHTML:false});const data:Record<string,unknown[][]>={};for(const name of book.SheetNames){const worksheet=book.Sheets[name];if(worksheet['!fullref']&&XLSX.utils.decode_range(worksheet['!fullref']).e.r>=10001)throw Error('시트당 10,000행 이하로 나누어 가져와 주세요.');data[name]=XLSX.utils.sheet_to_json(worksheet,{header:1,defval:'',raw:false});}if(!book.SheetNames.length)throw Error('시트가 없습니다.');setSheets(data);select(book.SheetNames[0],data);}catch(e){setError(e instanceof Error&&/선택|이하|시트/.test(e.message)?e.message:'파일을 읽지 못했습니다. 암호를 해제한 정상 Excel 파일인지 확인해 주세요.');}finally{setBusy(false);}}
 return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent className="wide-dialog"><DialogTitle>학생 명단 엑셀 가져오기</DialogTitle><DialogDescription>나이스에서 내려받은 명단의 시트와 열을 확인하세요. 이름·학년·반·번호만 가져옵니다.</DialogDescription><div className="form-body import-form"><p className="notice">파일은 서버로 전송하지 않습니다. 가져온 명단과 작성한 기록은 현재 탭의 메모리에만 보관되며, 새로고침하거나 탭을 닫으면 삭제됩니다.</p><label className="field">엑셀 파일 (.xlsx, .xls · 최대 10MB)<input type="file" accept=".xlsx,.xls" disabled={busy} onChange={e=>void load(e.target.files?.[0])}/></label>{busy&&<p role="status">파일을 읽는 중…</p>}{error&&<p role="alert" className="error">{error}</p>}{sheet&&<label className="field">시트<select value={sheet} onChange={e=>select(e.target.value)}>{Object.keys(sheets).map(n=><option key={n}>{n}</option>)}</select></label>}{sheet&&!rows.length&&<p role="status">선택한 시트가 비어 있습니다. 다른 시트나 명단 파일을 선택해 주세요.</p>}{rows.length>0&&<><div className="form-grid"><label className="field">제목 행 번호<input type="number" min={1} max={rows.length} value={header+1} onChange={e=>{const h=Math.max(0,Math.min(rows.length-1,Number(e.target.value)-1));setHeader(h);setColumns(detectHeader([rows[h]]).columns);}}/></label></div><div className="form-grid">{(['name','grade','room','number'] as const).map((key,i)=><label className="field" key={key}>{['이름 열','학년 열','반 열','번호 열'][i]}<select value={columns[key]} onChange={e=>setColumns({...columns,[key]:Number(e.target.value)})}><option value={-1}>{key==='grade'||key==='room'?'직접 입력':'선택하세요'}</option>{rows[header]?.map((v,index)=><option key={index} value={index}>{index+1}열 · {String(v||'제목 없음')}</option>)}</select></label>)}{columns.grade<0&&<label className="field">공통 학년<input type="number" min={1} max={6} value={grade} onChange={e=>setGrade(e.target.value)}/></label>}{columns.room<0&&<label className="field">공통 반<input type="number" min={1} max={100} value={room} onChange={e=>setRoom(e.target.value)}/></label>}</div><p>새 학생 {preview.students.length}명 · 이미 등록된 동일 학생 {preview.skipped}명 제외 · 오류 {preview.errors.length}건</p>{preview.errors.length>0&&<div role="alert" className="error">{preview.errors.slice(0,5).map((v,i)=><p key={i}>{v}</p>)}<p>오류를 모두 수정한 뒤 가져올 수 있습니다.</p></div>}<div className="import-preview"><table><thead><tr><th>이름</th><th>학년</th><th>반</th><th>번호</th></tr></thead><tbody>{preview.students.slice(0,50).map(s=><tr key={s.id}><td>{s.name}</td><td>{s.grade}</td><td>{s.room}</td><td>{s.number}</td></tr>)}</tbody></table></div><p className="muted">최대 50명 미리보기 · 선택한 시트만 추가합니다. 기존 학생과 방문 이력은 유지합니다.</p><button className="primary" disabled={busy||!!preview.errors.length||!preview.students.length} onClick={()=>{if(lock.current)return;lock.current=true;onImport(preview.students);}}>학생 {preview.students.length}명 가져오기</button></>}</div></DialogContent></Dialog>
}
